[package]
name = "z3_sched"
version = "0.1.0"

[dependencies]
z3 = { git = "https://github.com/onai/z3-rs" }
serde_json = "1.0.26"
libc = "0.2"

[lib]
name = "z3_sched"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "json_sched"
path = "src/json_sched.rs"